/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_SCG_Configuration_v13c0_H_
#define	_LTE_SCG_Configuration_v13c0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LTE_SCG_Configuration_v13c0_PR {
	LTE_SCG_Configuration_v13c0_PR_NOTHING,	/* No components present */
	LTE_SCG_Configuration_v13c0_PR_release,
	LTE_SCG_Configuration_v13c0_PR_setup
} LTE_SCG_Configuration_v13c0_PR;

/* Forward declarations */
struct LTE_SCG_ConfigPartSCG_v13c0;

/* LTE_SCG-Configuration-v13c0 */
typedef struct LTE_SCG_Configuration_v13c0 {
	LTE_SCG_Configuration_v13c0_PR present;
	union LTE_SCG_Configuration_v13c0_u {
		NULL_t	 release;
		struct LTE_SCG_Configuration_v13c0__setup {
			struct LTE_SCG_ConfigPartSCG_v13c0	*scg_ConfigPartSCG_v13c0;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_SCG_Configuration_v13c0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_SCG_Configuration_v13c0;
extern asn_CHOICE_specifics_t asn_SPC_LTE_SCG_Configuration_v13c0_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_SCG_Configuration_v13c0_1[2];
extern asn_per_constraints_t asn_PER_type_LTE_SCG_Configuration_v13c0_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LTE_SCG-ConfigPartSCG-v13c0.h"

#endif	/* _LTE_SCG_Configuration_v13c0_H_ */
#include <asn_internal.h>
