/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_SystemInformationBlockType24_r15_H_
#define	_LTE_SystemInformationBlockType24_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LTE_T-Reselection.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LTE_CarrierFreqListNR_r15;
struct LTE_SpeedStateScaleFactors;

/* LTE_SystemInformationBlockType24-r15 */
typedef struct LTE_SystemInformationBlockType24_r15 {
	struct LTE_CarrierFreqListNR_r15	*carrierFreqListNR_r15;	/* OPTIONAL */
	LTE_T_Reselection_t	 t_ReselectionNR_r15;
	struct LTE_SpeedStateScaleFactors	*t_ReselectionNR_SF_r15;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_SystemInformationBlockType24_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_SystemInformationBlockType24_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_SystemInformationBlockType24_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_SystemInformationBlockType24_r15_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LTE_CarrierFreqListNR-r15.h"
#include "LTE_SpeedStateScaleFactors.h"

#endif	/* _LTE_SystemInformationBlockType24_r15_H_ */
#include <asn_internal.h>
