/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_RRCConnectionRequest_H_
#define	_LTE_RRCConnectionRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LTE_RRCConnectionRequest-r8-IEs.h"
#include "LTE_RRCConnectionRequest-5GC-r15-IEs.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LTE_RRCConnectionRequest__criticalExtensions_PR {
	LTE_RRCConnectionRequest__criticalExtensions_PR_NOTHING,	/* No components present */
	LTE_RRCConnectionRequest__criticalExtensions_PR_rrcConnectionRequest_r8,
	LTE_RRCConnectionRequest__criticalExtensions_PR_rrcConnectionRequest_r15
} LTE_RRCConnectionRequest__criticalExtensions_PR;

/* LTE_RRCConnectionRequest */
typedef struct LTE_RRCConnectionRequest {
	struct LTE_RRCConnectionRequest__criticalExtensions {
		LTE_RRCConnectionRequest__criticalExtensions_PR present;
		union LTE_RRCConnectionRequest__LTE_criticalExtensions_u {
			LTE_RRCConnectionRequest_r8_IEs_t	 rrcConnectionRequest_r8;
			LTE_RRCConnectionRequest_5GC_r15_IEs_t	 rrcConnectionRequest_r15;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_RRCConnectionRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_RRCConnectionRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_RRCConnectionRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_RRCConnectionRequest_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_RRCConnectionRequest_H_ */
#include <asn_internal.h>
