/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_SecurityConfigHO_v1530_H_
#define	_LTE_SecurityConfigHO_v1530_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "LTE_NextHopChainingCount.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include "LTE_SecurityAlgorithmConfig.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LTE_SecurityConfigHO_v1530__handoverType_v1530_PR {
	LTE_SecurityConfigHO_v1530__handoverType_v1530_PR_NOTHING,	/* No components present */
	LTE_SecurityConfigHO_v1530__handoverType_v1530_PR_intra5GC_r15,
	LTE_SecurityConfigHO_v1530__handoverType_v1530_PR_fivegc_ToEPC_r15,
	LTE_SecurityConfigHO_v1530__handoverType_v1530_PR_epc_To5GC_r15
} LTE_SecurityConfigHO_v1530__handoverType_v1530_PR;

/* Forward declarations */
struct LTE_SecurityAlgorithmConfig;

/* LTE_SecurityConfigHO-v1530 */
typedef struct LTE_SecurityConfigHO_v1530 {
	struct LTE_SecurityConfigHO_v1530__handoverType_v1530 {
		LTE_SecurityConfigHO_v1530__handoverType_v1530_PR present;
		union LTE_SecurityConfigHO_v1530__LTE_handoverType_v1530_u {
			struct LTE_SecurityConfigHO_v1530__handoverType_v1530__intra5GC_r15 {
				struct LTE_SecurityAlgorithmConfig	*securityAlgorithmConfig_r15;	/* OPTIONAL */
				BOOLEAN_t	 keyChangeIndicator_r15;
				LTE_NextHopChainingCount_t	 nextHopChainingCount_r15;
				OCTET_STRING_t	*nas_Container_r15;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} intra5GC_r15;
			struct LTE_SecurityConfigHO_v1530__handoverType_v1530__fivegc_ToEPC_r15 {
				LTE_SecurityAlgorithmConfig_t	 securityAlgorithmConfig_r15;
				LTE_NextHopChainingCount_t	 nextHopChainingCount_r15;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fivegc_ToEPC_r15;
			struct LTE_SecurityConfigHO_v1530__handoverType_v1530__epc_To5GC_r15 {
				LTE_SecurityAlgorithmConfig_t	 securityAlgorithmConfig_r15;
				OCTET_STRING_t	 nas_Container_r15;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} epc_To5GC_r15;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} handoverType_v1530;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_SecurityConfigHO_v1530_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_SecurityConfigHO_v1530;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_SecurityConfigHO_v1530_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_SecurityConfigHO_v1530_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LTE_SecurityAlgorithmConfig.h"

#endif	/* _LTE_SecurityConfigHO_v1530_H_ */
#include <asn_internal.h>
