/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_CGI_InfoNR_r15_H_
#define	_LTE_CGI_InfoNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LTE_PLMN_IdentityInfoListNR_r15;
struct LTE_MultiFrequencyBandListNR_r15;

/* LTE_CGI-InfoNR-r15 */
typedef struct LTE_CGI_InfoNR_r15 {
	struct LTE_PLMN_IdentityInfoListNR_r15	*plmn_IdentityInfoList_r15;	/* OPTIONAL */
	struct LTE_MultiFrequencyBandListNR_r15	*frequencyBandList_15;	/* OPTIONAL */
	struct LTE_CGI_InfoNR_r15__noSIB1_r15 {
		long	 ssb_SubcarrierOffset_r15;
		long	 pdcch_ConfigSIB1_r15;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *noSIB1_r15;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_CGI_InfoNR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_CGI_InfoNR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_CGI_InfoNR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_CGI_InfoNR_r15_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LTE_PLMN-IdentityInfoListNR-r15.h"
#include "LTE_MultiFrequencyBandListNR-r15.h"

#endif	/* _LTE_CGI_InfoNR_r15_H_ */
#include <asn_internal.h>
