/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_RRCConnectionSetupComplete_v1540_IEs_H_
#define	_LTE_RRCConnectionSetupComplete_v1540_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LTE_RRCConnectionSetupComplete_v1540_IEs__gummei_Type_v1540 {
	LTE_RRCConnectionSetupComplete_v1540_IEs__gummei_Type_v1540_mappedFrom5G	= 0
} e_LTE_RRCConnectionSetupComplete_v1540_IEs__gummei_Type_v1540;
typedef enum LTE_RRCConnectionSetupComplete_v1540_IEs__guami_Type_r15 {
	LTE_RRCConnectionSetupComplete_v1540_IEs__guami_Type_r15_native	= 0,
	LTE_RRCConnectionSetupComplete_v1540_IEs__guami_Type_r15_mapped	= 1
} e_LTE_RRCConnectionSetupComplete_v1540_IEs__guami_Type_r15;

/* LTE_RRCConnectionSetupComplete-v1540-IEs */
typedef struct LTE_RRCConnectionSetupComplete_v1540_IEs {
	long	*gummei_Type_v1540;	/* OPTIONAL */
	long	*guami_Type_r15;	/* OPTIONAL */
	struct LTE_RRCConnectionSetupComplete_v1540_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_RRCConnectionSetupComplete_v1540_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LTE_gummei_Type_v1540_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LTE_guami_Type_r15_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LTE_RRCConnectionSetupComplete_v1540_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_RRCConnectionSetupComplete_v1540_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_RRCConnectionSetupComplete_v1540_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_RRCConnectionSetupComplete_v1540_IEs_H_ */
#include <asn_internal.h>
