/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_RRCConnectionResumeRequest_5GC_r15_IEs_H_
#define	_LTE_RRCConnectionResumeRequest_5GC_r15_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "LTE_ResumeCause-r15.h"
#include "LTE_I-RNTI-r15.h"
#include "LTE_ShortI-RNTI-r15.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR {
	LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR_NOTHING,	/* No components present */
	LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR_fullI_RNTI_r15,
	LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR_shortI_RNTI_r15
} LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR;

/* LTE_RRCConnectionResumeRequest-5GC-r15-IEs */
typedef struct LTE_RRCConnectionResumeRequest_5GC_r15_IEs {
	struct LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15 {
		LTE_RRCConnectionResumeRequest_5GC_r15_IEs__resumeIdentity_r15_PR present;
		union LTE_RRCConnectionResumeRequest_5GC_r15_IEs__LTE_resumeIdentity_r15_u {
			LTE_I_RNTI_r15_t	 fullI_RNTI_r15;
			LTE_ShortI_RNTI_r15_t	 shortI_RNTI_r15;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resumeIdentity_r15;
	BIT_STRING_t	 shortResumeMAC_I_r15;
	LTE_ResumeCause_r15_t	 resumeCause_r15;
	BIT_STRING_t	 spare;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_RRCConnectionResumeRequest_5GC_r15_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_RRCConnectionResumeRequest_5GC_r15_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_RRCConnectionResumeRequest_5GC_r15_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_RRCConnectionResumeRequest_5GC_r15_IEs_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_RRCConnectionResumeRequest_5GC_r15_IEs_H_ */
#include <asn_internal.h>
