/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_RedirectedCarrierInfo_NB_v1550_H_
#define	_LTE_RedirectedCarrierInfo_NB_v1550_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LTE_CarrierFreq-NB-v1550.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LTE_RedirectedCarrierInfo-NB-v1550 */
typedef LTE_CarrierFreq_NB_v1550_t	 LTE_RedirectedCarrierInfo_NB_v1550_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_RedirectedCarrierInfo_NB_v1550;
asn_struct_free_f LTE_RedirectedCarrierInfo_NB_v1550_free;
asn_struct_print_f LTE_RedirectedCarrierInfo_NB_v1550_print;
asn_constr_check_f LTE_RedirectedCarrierInfo_NB_v1550_constraint;
ber_type_decoder_f LTE_RedirectedCarrierInfo_NB_v1550_decode_ber;
der_type_encoder_f LTE_RedirectedCarrierInfo_NB_v1550_encode_der;
xer_type_decoder_f LTE_RedirectedCarrierInfo_NB_v1550_decode_xer;
xer_type_encoder_f LTE_RedirectedCarrierInfo_NB_v1550_encode_xer;
per_type_decoder_f LTE_RedirectedCarrierInfo_NB_v1550_decode_uper;
per_type_encoder_f LTE_RedirectedCarrierInfo_NB_v1550_encode_uper;
per_type_decoder_f LTE_RedirectedCarrierInfo_NB_v1550_decode_aper;
per_type_encoder_f LTE_RedirectedCarrierInfo_NB_v1550_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_RedirectedCarrierInfo_NB_v1550_H_ */
#include <asn_internal.h>
