/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "lte-rrc-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -D lte-rrc-15.6.0.gen`
 */

#ifndef	_LTE_QuantityConfigRS_NR_r15_H_
#define	_LTE_QuantityConfigRS_NR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LTE_FilterCoefficient.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LTE_QuantityConfigRS-NR-r15 */
typedef struct LTE_QuantityConfigRS_NR_r15 {
	LTE_FilterCoefficient_t	*filterCoeff_RSRP_r15;	/* DEFAULT 4 */
	LTE_FilterCoefficient_t	*filterCoeff_RSRQ_r15;	/* DEFAULT 4 */
	LTE_FilterCoefficient_t	*filterCoefficient_SINR_r13;	/* DEFAULT 4 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LTE_QuantityConfigRS_NR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LTE_QuantityConfigRS_NR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_LTE_QuantityConfigRS_NR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_LTE_QuantityConfigRS_NR_r15_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LTE_QuantityConfigRS_NR_r15_H_ */
#include <asn_internal.h>
