/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_CrossCarrierSchedulingConfig_H_
#define	_NR_CrossCarrierSchedulingConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include "NR_ServCellIndex.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR {
	NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR_NOTHING,	/* No components present */
	NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR_own,
	NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR_other
} NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR;

/* NR_CrossCarrierSchedulingConfig */
typedef struct NR_CrossCarrierSchedulingConfig {
	struct NR_CrossCarrierSchedulingConfig__schedulingCellInfo {
		NR_CrossCarrierSchedulingConfig__schedulingCellInfo_PR present;
		union NR_CrossCarrierSchedulingConfig__NR_schedulingCellInfo_u {
			struct NR_CrossCarrierSchedulingConfig__schedulingCellInfo__own {
				BOOLEAN_t	 cif_Presence;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *own;
			struct NR_CrossCarrierSchedulingConfig__schedulingCellInfo__other {
				NR_ServCellIndex_t	 schedulingCellId;
				long	 cif_InSchedulingCell;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *other;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} schedulingCellInfo;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct NR_CrossCarrierSchedulingConfig__ext1 {
		struct NR_CrossCarrierSchedulingConfig__ext1__carrierIndicatorSize {
			long	 carrierIndicatorSizeForDCI_Format1_2_r16;
			long	 carrierIndicatorSizeForDCI_Format0_2_r16;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *carrierIndicatorSize;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_CrossCarrierSchedulingConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_CrossCarrierSchedulingConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_CrossCarrierSchedulingConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_CrossCarrierSchedulingConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_CrossCarrierSchedulingConfig_H_ */
#include <asn_internal.h>
