/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#include "NR_MeasAndMobParametersCommon.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_NR_supportedGapPattern_NRonly_r16_constraint_43(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_supportedGapPattern_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 22)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_NR_ssb_RLM_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_ssb_AndCSI_RS_RLM_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_eventB_MeasAndReport_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_handoverFDD_TDD_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_eutra_CGI_Reporting_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_CGI_Reporting_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_independentGapConfig_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_periodicEUTRA_MeasAndReport_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_handoverFR1_FR2_constr_22 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_maxNumberCSI_RS_RRM_RS_SINR_constr_24 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_CGI_Reporting_ENDC_constr_32 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_eutra_CGI_Reporting_NEDC_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_eutra_CGI_Reporting_NRDC_constr_37 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_CGI_Reporting_NEDC_constr_39 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_CGI_Reporting_NRDC_constr_41 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_reportAddNeighMeasForPeriodic_r16_constr_44 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_condHandoverFDD_TDD_r16_constr_47 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_condHandoverFR1_FR2_r16_constr_49 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_NeedForGap_Reporting_r16_constr_51 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_supportedGapPattern_NRonly_NEDC_r16_constr_54 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_maxNumberCLI_RSSI_r16_constr_56 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_maxNumberCLI_SRS_RSRP_r16_constr_61 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_constr_66 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_mfbi_IAB_r16_constr_70 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_multipleNS_And_Pmax_IAB_r16_constr_72 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_nr_CGI_Reporting_NPN_r16_constr_74 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_idleInactiveEUTRA_MeasReport_r16_constr_76 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_idleInactive_ValidityArea_r16_constr_78 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_supportedGapPattern_NRonly_r16_constr_53 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  10,  10 }	/* (SIZE(10..10)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_supportedGapPattern_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  22,  22 }	/* (SIZE(22..22)) */,
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_NR_ssb_RLM_value2enum_3[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_ssb_RLM_enum2value_3[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_ssb_RLM_specs_3 = {
	asn_MAP_NR_ssb_RLM_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_ssb_RLM_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_ssb_RLM_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ssb_RLM_3 = {
	"ssb-RLM",
	"ssb-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_ssb_RLM_tags_3,
	sizeof(asn_DEF_NR_ssb_RLM_tags_3)
		/sizeof(asn_DEF_NR_ssb_RLM_tags_3[0]) - 1, /* 1 */
	asn_DEF_NR_ssb_RLM_tags_3,	/* Same as above */
	sizeof(asn_DEF_NR_ssb_RLM_tags_3)
		/sizeof(asn_DEF_NR_ssb_RLM_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_NR_ssb_RLM_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_ssb_RLM_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_ssb_AndCSI_RS_RLM_value2enum_5[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_ssb_AndCSI_RS_RLM_enum2value_5[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_ssb_AndCSI_RS_RLM_specs_5 = {
	asn_MAP_NR_ssb_AndCSI_RS_RLM_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_ssb_AndCSI_RS_RLM_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ssb_AndCSI_RS_RLM_5 = {
	"ssb-AndCSI-RS-RLM",
	"ssb-AndCSI-RS-RLM",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5,
	sizeof(asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5)
		/sizeof(asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5[0]) - 1, /* 1 */
	asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5,	/* Same as above */
	sizeof(asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5)
		/sizeof(asn_DEF_NR_ssb_AndCSI_RS_RLM_tags_5[0]), /* 2 */
	{ 0, &asn_PER_type_NR_ssb_AndCSI_RS_RLM_constr_5, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_ssb_AndCSI_RS_RLM_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_eventB_MeasAndReport_value2enum_9[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_eventB_MeasAndReport_enum2value_9[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_eventB_MeasAndReport_specs_9 = {
	asn_MAP_NR_eventB_MeasAndReport_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_eventB_MeasAndReport_enum2value_9,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_eventB_MeasAndReport_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_eventB_MeasAndReport_9 = {
	"eventB-MeasAndReport",
	"eventB-MeasAndReport",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_eventB_MeasAndReport_tags_9,
	sizeof(asn_DEF_NR_eventB_MeasAndReport_tags_9)
		/sizeof(asn_DEF_NR_eventB_MeasAndReport_tags_9[0]) - 1, /* 1 */
	asn_DEF_NR_eventB_MeasAndReport_tags_9,	/* Same as above */
	sizeof(asn_DEF_NR_eventB_MeasAndReport_tags_9)
		/sizeof(asn_DEF_NR_eventB_MeasAndReport_tags_9[0]), /* 2 */
	{ 0, &asn_PER_type_NR_eventB_MeasAndReport_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_eventB_MeasAndReport_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_handoverFDD_TDD_value2enum_11[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_handoverFDD_TDD_enum2value_11[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_handoverFDD_TDD_specs_11 = {
	asn_MAP_NR_handoverFDD_TDD_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_handoverFDD_TDD_enum2value_11,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_handoverFDD_TDD_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_handoverFDD_TDD_11 = {
	"handoverFDD-TDD",
	"handoverFDD-TDD",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_handoverFDD_TDD_tags_11,
	sizeof(asn_DEF_NR_handoverFDD_TDD_tags_11)
		/sizeof(asn_DEF_NR_handoverFDD_TDD_tags_11[0]) - 1, /* 1 */
	asn_DEF_NR_handoverFDD_TDD_tags_11,	/* Same as above */
	sizeof(asn_DEF_NR_handoverFDD_TDD_tags_11)
		/sizeof(asn_DEF_NR_handoverFDD_TDD_tags_11[0]), /* 2 */
	{ 0, &asn_PER_type_NR_handoverFDD_TDD_constr_11, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_handoverFDD_TDD_specs_11	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_eutra_CGI_Reporting_value2enum_13[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_eutra_CGI_Reporting_enum2value_13[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_eutra_CGI_Reporting_specs_13 = {
	asn_MAP_NR_eutra_CGI_Reporting_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_eutra_CGI_Reporting_enum2value_13,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_eutra_CGI_Reporting_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_eutra_CGI_Reporting_13 = {
	"eutra-CGI-Reporting",
	"eutra-CGI-Reporting",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_eutra_CGI_Reporting_tags_13,
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_tags_13)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_tags_13[0]) - 1, /* 1 */
	asn_DEF_NR_eutra_CGI_Reporting_tags_13,	/* Same as above */
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_tags_13)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_tags_13[0]), /* 2 */
	{ 0, &asn_PER_type_NR_eutra_CGI_Reporting_constr_13, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_eutra_CGI_Reporting_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_CGI_Reporting_value2enum_15[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_CGI_Reporting_enum2value_15[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_CGI_Reporting_specs_15 = {
	asn_MAP_NR_nr_CGI_Reporting_value2enum_15,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_CGI_Reporting_enum2value_15,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_CGI_Reporting_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_CGI_Reporting_15 = {
	"nr-CGI-Reporting",
	"nr-CGI-Reporting",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_CGI_Reporting_tags_15,
	sizeof(asn_DEF_NR_nr_CGI_Reporting_tags_15)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_tags_15[0]) - 1, /* 1 */
	asn_DEF_NR_nr_CGI_Reporting_tags_15,	/* Same as above */
	sizeof(asn_DEF_NR_nr_CGI_Reporting_tags_15)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_tags_15[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_CGI_Reporting_constr_15, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_CGI_Reporting_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext1_8[] = {
	{ ATF_POINTER, 4, offsetof(struct NR_MeasAndMobParametersCommon__ext1, eventB_MeasAndReport),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_eventB_MeasAndReport_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventB-MeasAndReport"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_MeasAndMobParametersCommon__ext1, handoverFDD_TDD),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_handoverFDD_TDD_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverFDD-TDD"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon__ext1, eutra_CGI_Reporting),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_eutra_CGI_Reporting_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext1, nr_CGI_Reporting),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_CGI_Reporting_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting"
		},
};
static const int asn_MAP_NR_ext1_oms_8[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_NR_ext1_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext1_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventB-MeasAndReport */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* handoverFDD-TDD */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eutra-CGI-Reporting */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nr-CGI-Reporting */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext1_specs_8 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext1),
	offsetof(struct NR_MeasAndMobParametersCommon__ext1, _asn_ctx),
	asn_MAP_NR_ext1_tag2el_8,
	4,	/* Count of tags in the map */
	asn_MAP_NR_ext1_oms_8,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext1_8 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext1_tags_8,
	sizeof(asn_DEF_NR_ext1_tags_8)
		/sizeof(asn_DEF_NR_ext1_tags_8[0]) - 1, /* 1 */
	asn_DEF_NR_ext1_tags_8,	/* Same as above */
	sizeof(asn_DEF_NR_ext1_tags_8)
		/sizeof(asn_DEF_NR_ext1_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext1_8,
	4,	/* Elements count */
	&asn_SPC_NR_ext1_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_independentGapConfig_value2enum_18[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_independentGapConfig_enum2value_18[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_independentGapConfig_specs_18 = {
	asn_MAP_NR_independentGapConfig_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_independentGapConfig_enum2value_18,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_independentGapConfig_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_independentGapConfig_18 = {
	"independentGapConfig",
	"independentGapConfig",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_independentGapConfig_tags_18,
	sizeof(asn_DEF_NR_independentGapConfig_tags_18)
		/sizeof(asn_DEF_NR_independentGapConfig_tags_18[0]) - 1, /* 1 */
	asn_DEF_NR_independentGapConfig_tags_18,	/* Same as above */
	sizeof(asn_DEF_NR_independentGapConfig_tags_18)
		/sizeof(asn_DEF_NR_independentGapConfig_tags_18[0]), /* 2 */
	{ 0, &asn_PER_type_NR_independentGapConfig_constr_18, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_independentGapConfig_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_periodicEUTRA_MeasAndReport_value2enum_20[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_periodicEUTRA_MeasAndReport_enum2value_20[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_periodicEUTRA_MeasAndReport_specs_20 = {
	asn_MAP_NR_periodicEUTRA_MeasAndReport_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_periodicEUTRA_MeasAndReport_enum2value_20,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_periodicEUTRA_MeasAndReport_20 = {
	"periodicEUTRA-MeasAndReport",
	"periodicEUTRA-MeasAndReport",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20,
	sizeof(asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20)
		/sizeof(asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20[0]) - 1, /* 1 */
	asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20,	/* Same as above */
	sizeof(asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20)
		/sizeof(asn_DEF_NR_periodicEUTRA_MeasAndReport_tags_20[0]), /* 2 */
	{ 0, &asn_PER_type_NR_periodicEUTRA_MeasAndReport_constr_20, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_periodicEUTRA_MeasAndReport_specs_20	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_handoverFR1_FR2_value2enum_22[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_handoverFR1_FR2_enum2value_22[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_handoverFR1_FR2_specs_22 = {
	asn_MAP_NR_handoverFR1_FR2_value2enum_22,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_handoverFR1_FR2_enum2value_22,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_handoverFR1_FR2_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_handoverFR1_FR2_22 = {
	"handoverFR1-FR2",
	"handoverFR1-FR2",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_handoverFR1_FR2_tags_22,
	sizeof(asn_DEF_NR_handoverFR1_FR2_tags_22)
		/sizeof(asn_DEF_NR_handoverFR1_FR2_tags_22[0]) - 1, /* 1 */
	asn_DEF_NR_handoverFR1_FR2_tags_22,	/* Same as above */
	sizeof(asn_DEF_NR_handoverFR1_FR2_tags_22)
		/sizeof(asn_DEF_NR_handoverFR1_FR2_tags_22[0]), /* 2 */
	{ 0, &asn_PER_type_NR_handoverFR1_FR2_constr_22, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_handoverFR1_FR2_specs_22	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_maxNumberCSI_RS_RRM_RS_SINR_value2enum_24[] = {
	{ 0,	2,	"n4" },
	{ 1,	2,	"n8" },
	{ 2,	3,	"n16" },
	{ 3,	3,	"n32" },
	{ 4,	3,	"n64" },
	{ 5,	3,	"n96" }
};
static const unsigned int asn_MAP_NR_maxNumberCSI_RS_RRM_RS_SINR_enum2value_24[] = {
	2,	/* n16(2) */
	3,	/* n32(3) */
	0,	/* n4(0) */
	4,	/* n64(4) */
	1,	/* n8(1) */
	5	/* n96(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_maxNumberCSI_RS_RRM_RS_SINR_specs_24 = {
	asn_MAP_NR_maxNumberCSI_RS_RRM_RS_SINR_value2enum_24,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_maxNumberCSI_RS_RRM_RS_SINR_enum2value_24,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_24 = {
	"maxNumberCSI-RS-RRM-RS-SINR",
	"maxNumberCSI-RS-RRM-RS-SINR",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24,
	sizeof(asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24)
		/sizeof(asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24[0]) - 1, /* 1 */
	asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24,	/* Same as above */
	sizeof(asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24)
		/sizeof(asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_tags_24[0]), /* 2 */
	{ 0, &asn_PER_type_NR_maxNumberCSI_RS_RRM_RS_SINR_constr_24, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_maxNumberCSI_RS_RRM_RS_SINR_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext2_17[] = {
	{ ATF_POINTER, 4, offsetof(struct NR_MeasAndMobParametersCommon__ext2, independentGapConfig),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_independentGapConfig_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"independentGapConfig"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_MeasAndMobParametersCommon__ext2, periodicEUTRA_MeasAndReport),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_periodicEUTRA_MeasAndReport_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodicEUTRA-MeasAndReport"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon__ext2, handoverFR1_FR2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_handoverFR1_FR2_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handoverFR1-FR2"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext2, maxNumberCSI_RS_RRM_RS_SINR),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_maxNumberCSI_RS_RRM_RS_SINR_24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberCSI-RS-RRM-RS-SINR"
		},
};
static const int asn_MAP_NR_ext2_oms_17[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_NR_ext2_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext2_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* independentGapConfig */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* periodicEUTRA-MeasAndReport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* handoverFR1-FR2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* maxNumberCSI-RS-RRM-RS-SINR */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext2_specs_17 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext2),
	offsetof(struct NR_MeasAndMobParametersCommon__ext2, _asn_ctx),
	asn_MAP_NR_ext2_tag2el_17,
	4,	/* Count of tags in the map */
	asn_MAP_NR_ext2_oms_17,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext2_17 = {
	"ext2",
	"ext2",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext2_tags_17,
	sizeof(asn_DEF_NR_ext2_tags_17)
		/sizeof(asn_DEF_NR_ext2_tags_17[0]) - 1, /* 1 */
	asn_DEF_NR_ext2_tags_17,	/* Same as above */
	sizeof(asn_DEF_NR_ext2_tags_17)
		/sizeof(asn_DEF_NR_ext2_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext2_17,
	4,	/* Elements count */
	&asn_SPC_NR_ext2_specs_17	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_CGI_Reporting_ENDC_value2enum_32[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_CGI_Reporting_ENDC_enum2value_32[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_CGI_Reporting_ENDC_specs_32 = {
	asn_MAP_NR_nr_CGI_Reporting_ENDC_value2enum_32,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_CGI_Reporting_ENDC_enum2value_32,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_CGI_Reporting_ENDC_32 = {
	"nr-CGI-Reporting-ENDC",
	"nr-CGI-Reporting-ENDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32,
	sizeof(asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32[0]) - 1, /* 1 */
	asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32,	/* Same as above */
	sizeof(asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_ENDC_tags_32[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_CGI_Reporting_ENDC_constr_32, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_CGI_Reporting_ENDC_specs_32	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext3_31[] = {
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext3, nr_CGI_Reporting_ENDC),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_CGI_Reporting_ENDC_32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-ENDC"
		},
};
static const int asn_MAP_NR_ext3_oms_31[] = { 0 };
static const ber_tlv_tag_t asn_DEF_NR_ext3_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext3_tag2el_31[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* nr-CGI-Reporting-ENDC */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext3_specs_31 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext3),
	offsetof(struct NR_MeasAndMobParametersCommon__ext3, _asn_ctx),
	asn_MAP_NR_ext3_tag2el_31,
	1,	/* Count of tags in the map */
	asn_MAP_NR_ext3_oms_31,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext3_31 = {
	"ext3",
	"ext3",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext3_tags_31,
	sizeof(asn_DEF_NR_ext3_tags_31)
		/sizeof(asn_DEF_NR_ext3_tags_31[0]) - 1, /* 1 */
	asn_DEF_NR_ext3_tags_31,	/* Same as above */
	sizeof(asn_DEF_NR_ext3_tags_31)
		/sizeof(asn_DEF_NR_ext3_tags_31[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext3_31,
	1,	/* Elements count */
	&asn_SPC_NR_ext3_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_eutra_CGI_Reporting_NEDC_value2enum_35[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_eutra_CGI_Reporting_NEDC_enum2value_35[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_eutra_CGI_Reporting_NEDC_specs_35 = {
	asn_MAP_NR_eutra_CGI_Reporting_NEDC_value2enum_35,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_eutra_CGI_Reporting_NEDC_enum2value_35,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_eutra_CGI_Reporting_NEDC_35 = {
	"eutra-CGI-Reporting-NEDC",
	"eutra-CGI-Reporting-NEDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35,
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35[0]) - 1, /* 1 */
	asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35,	/* Same as above */
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_NEDC_tags_35[0]), /* 2 */
	{ 0, &asn_PER_type_NR_eutra_CGI_Reporting_NEDC_constr_35, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_eutra_CGI_Reporting_NEDC_specs_35	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_eutra_CGI_Reporting_NRDC_value2enum_37[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_eutra_CGI_Reporting_NRDC_enum2value_37[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_eutra_CGI_Reporting_NRDC_specs_37 = {
	asn_MAP_NR_eutra_CGI_Reporting_NRDC_value2enum_37,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_eutra_CGI_Reporting_NRDC_enum2value_37,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_eutra_CGI_Reporting_NRDC_37 = {
	"eutra-CGI-Reporting-NRDC",
	"eutra-CGI-Reporting-NRDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37,
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37[0]) - 1, /* 1 */
	asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37,	/* Same as above */
	sizeof(asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37)
		/sizeof(asn_DEF_NR_eutra_CGI_Reporting_NRDC_tags_37[0]), /* 2 */
	{ 0, &asn_PER_type_NR_eutra_CGI_Reporting_NRDC_constr_37, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_eutra_CGI_Reporting_NRDC_specs_37	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_CGI_Reporting_NEDC_value2enum_39[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_CGI_Reporting_NEDC_enum2value_39[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_CGI_Reporting_NEDC_specs_39 = {
	asn_MAP_NR_nr_CGI_Reporting_NEDC_value2enum_39,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_CGI_Reporting_NEDC_enum2value_39,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_CGI_Reporting_NEDC_39 = {
	"nr-CGI-Reporting-NEDC",
	"nr-CGI-Reporting-NEDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39,
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39[0]) - 1, /* 1 */
	asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39,	/* Same as above */
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NEDC_tags_39[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_CGI_Reporting_NEDC_constr_39, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_CGI_Reporting_NEDC_specs_39	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_CGI_Reporting_NRDC_value2enum_41[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_CGI_Reporting_NRDC_enum2value_41[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_CGI_Reporting_NRDC_specs_41 = {
	asn_MAP_NR_nr_CGI_Reporting_NRDC_value2enum_41,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_CGI_Reporting_NRDC_enum2value_41,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_CGI_Reporting_NRDC_41 = {
	"nr-CGI-Reporting-NRDC",
	"nr-CGI-Reporting-NRDC",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41,
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41[0]) - 1, /* 1 */
	asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41,	/* Same as above */
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NRDC_tags_41[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_CGI_Reporting_NRDC_constr_41, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_CGI_Reporting_NRDC_specs_41	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext4_34[] = {
	{ ATF_POINTER, 4, offsetof(struct NR_MeasAndMobParametersCommon__ext4, eutra_CGI_Reporting_NEDC),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_eutra_CGI_Reporting_NEDC_35,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting-NEDC"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_MeasAndMobParametersCommon__ext4, eutra_CGI_Reporting_NRDC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_eutra_CGI_Reporting_NRDC_37,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-CGI-Reporting-NRDC"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon__ext4, nr_CGI_Reporting_NEDC),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_CGI_Reporting_NEDC_39,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-NEDC"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext4, nr_CGI_Reporting_NRDC),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_CGI_Reporting_NRDC_41,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-NRDC"
		},
};
static const int asn_MAP_NR_ext4_oms_34[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_NR_ext4_tags_34[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext4_tag2el_34[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eutra-CGI-Reporting-NEDC */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eutra-CGI-Reporting-NRDC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nr-CGI-Reporting-NEDC */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nr-CGI-Reporting-NRDC */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext4_specs_34 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext4),
	offsetof(struct NR_MeasAndMobParametersCommon__ext4, _asn_ctx),
	asn_MAP_NR_ext4_tag2el_34,
	4,	/* Count of tags in the map */
	asn_MAP_NR_ext4_oms_34,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext4_34 = {
	"ext4",
	"ext4",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext4_tags_34,
	sizeof(asn_DEF_NR_ext4_tags_34)
		/sizeof(asn_DEF_NR_ext4_tags_34[0]) - 1, /* 1 */
	asn_DEF_NR_ext4_tags_34,	/* Same as above */
	sizeof(asn_DEF_NR_ext4_tags_34)
		/sizeof(asn_DEF_NR_ext4_tags_34[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext4_34,
	4,	/* Elements count */
	&asn_SPC_NR_ext4_specs_34	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_reportAddNeighMeasForPeriodic_r16_value2enum_44[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_reportAddNeighMeasForPeriodic_r16_enum2value_44[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_reportAddNeighMeasForPeriodic_r16_specs_44 = {
	asn_MAP_NR_reportAddNeighMeasForPeriodic_r16_value2enum_44,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_reportAddNeighMeasForPeriodic_r16_enum2value_44,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_44 = {
	"reportAddNeighMeasForPeriodic-r16",
	"reportAddNeighMeasForPeriodic-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44,
	sizeof(asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44)
		/sizeof(asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44[0]) - 1, /* 1 */
	asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44,	/* Same as above */
	sizeof(asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44)
		/sizeof(asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_tags_44[0]), /* 2 */
	{ 0, &asn_PER_type_NR_reportAddNeighMeasForPeriodic_r16_constr_44, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_reportAddNeighMeasForPeriodic_r16_specs_44	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_condHandoverFDD_TDD_r16_value2enum_47[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_condHandoverFDD_TDD_r16_enum2value_47[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_condHandoverFDD_TDD_r16_specs_47 = {
	asn_MAP_NR_condHandoverFDD_TDD_r16_value2enum_47,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_condHandoverFDD_TDD_r16_enum2value_47,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_condHandoverFDD_TDD_r16_47 = {
	"condHandoverFDD-TDD-r16",
	"condHandoverFDD-TDD-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47,
	sizeof(asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47)
		/sizeof(asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47[0]) - 1, /* 1 */
	asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47,	/* Same as above */
	sizeof(asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47)
		/sizeof(asn_DEF_NR_condHandoverFDD_TDD_r16_tags_47[0]), /* 2 */
	{ 0, &asn_PER_type_NR_condHandoverFDD_TDD_r16_constr_47, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_condHandoverFDD_TDD_r16_specs_47	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_condHandoverFR1_FR2_r16_value2enum_49[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_condHandoverFR1_FR2_r16_enum2value_49[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_condHandoverFR1_FR2_r16_specs_49 = {
	asn_MAP_NR_condHandoverFR1_FR2_r16_value2enum_49,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_condHandoverFR1_FR2_r16_enum2value_49,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_condHandoverFR1_FR2_r16_49 = {
	"condHandoverFR1-FR2-r16",
	"condHandoverFR1-FR2-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49,
	sizeof(asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49)
		/sizeof(asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49[0]) - 1, /* 1 */
	asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49,	/* Same as above */
	sizeof(asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49)
		/sizeof(asn_DEF_NR_condHandoverFR1_FR2_r16_tags_49[0]), /* 2 */
	{ 0, &asn_PER_type_NR_condHandoverFR1_FR2_r16_constr_49, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_condHandoverFR1_FR2_r16_specs_49	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_condHandoverParametersCommon_r16_46[] = {
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon__ext5__condHandoverParametersCommon_r16, condHandoverFDD_TDD_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_condHandoverFDD_TDD_r16_47,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condHandoverFDD-TDD-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext5__condHandoverParametersCommon_r16, condHandoverFR1_FR2_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_condHandoverFR1_FR2_r16_49,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condHandoverFR1-FR2-r16"
		},
};
static const int asn_MAP_NR_condHandoverParametersCommon_r16_oms_46[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NR_condHandoverParametersCommon_r16_tags_46[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_condHandoverParametersCommon_r16_tag2el_46[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* condHandoverFDD-TDD-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* condHandoverFR1-FR2-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_condHandoverParametersCommon_r16_specs_46 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext5__condHandoverParametersCommon_r16),
	offsetof(struct NR_MeasAndMobParametersCommon__ext5__condHandoverParametersCommon_r16, _asn_ctx),
	asn_MAP_NR_condHandoverParametersCommon_r16_tag2el_46,
	2,	/* Count of tags in the map */
	asn_MAP_NR_condHandoverParametersCommon_r16_oms_46,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_condHandoverParametersCommon_r16_46 = {
	"condHandoverParametersCommon-r16",
	"condHandoverParametersCommon-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_condHandoverParametersCommon_r16_tags_46,
	sizeof(asn_DEF_NR_condHandoverParametersCommon_r16_tags_46)
		/sizeof(asn_DEF_NR_condHandoverParametersCommon_r16_tags_46[0]) - 1, /* 1 */
	asn_DEF_NR_condHandoverParametersCommon_r16_tags_46,	/* Same as above */
	sizeof(asn_DEF_NR_condHandoverParametersCommon_r16_tags_46)
		/sizeof(asn_DEF_NR_condHandoverParametersCommon_r16_tags_46[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_condHandoverParametersCommon_r16_46,
	2,	/* Elements count */
	&asn_SPC_NR_condHandoverParametersCommon_r16_specs_46	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_NeedForGap_Reporting_r16_value2enum_51[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_NeedForGap_Reporting_r16_enum2value_51[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_NeedForGap_Reporting_r16_specs_51 = {
	asn_MAP_NR_nr_NeedForGap_Reporting_r16_value2enum_51,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_NeedForGap_Reporting_r16_enum2value_51,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_NeedForGap_Reporting_r16_51 = {
	"nr-NeedForGap-Reporting-r16",
	"nr-NeedForGap-Reporting-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51,
	sizeof(asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51)
		/sizeof(asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51[0]) - 1, /* 1 */
	asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51,	/* Same as above */
	sizeof(asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51)
		/sizeof(asn_DEF_NR_nr_NeedForGap_Reporting_r16_tags_51[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_NeedForGap_Reporting_r16_constr_51, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_NeedForGap_Reporting_r16_specs_51	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_supportedGapPattern_NRonly_NEDC_r16_value2enum_54[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_supportedGapPattern_NRonly_NEDC_r16_enum2value_54[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_supportedGapPattern_NRonly_NEDC_r16_specs_54 = {
	asn_MAP_NR_supportedGapPattern_NRonly_NEDC_r16_value2enum_54,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_supportedGapPattern_NRonly_NEDC_r16_enum2value_54,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_54 = {
	"supportedGapPattern-NRonly-NEDC-r16",
	"supportedGapPattern-NRonly-NEDC-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54,
	sizeof(asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54)
		/sizeof(asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54[0]) - 1, /* 1 */
	asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54,	/* Same as above */
	sizeof(asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54)
		/sizeof(asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_tags_54[0]), /* 2 */
	{ 0, &asn_PER_type_NR_supportedGapPattern_NRonly_NEDC_r16_constr_54, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_supportedGapPattern_NRonly_NEDC_r16_specs_54	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_maxNumberCLI_RSSI_r16_value2enum_56[] = {
	{ 0,	2,	"n8" },
	{ 1,	3,	"n16" },
	{ 2,	3,	"n32" },
	{ 3,	3,	"n64" }
};
static const unsigned int asn_MAP_NR_maxNumberCLI_RSSI_r16_enum2value_56[] = {
	1,	/* n16(1) */
	2,	/* n32(2) */
	3,	/* n64(3) */
	0	/* n8(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_maxNumberCLI_RSSI_r16_specs_56 = {
	asn_MAP_NR_maxNumberCLI_RSSI_r16_value2enum_56,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_maxNumberCLI_RSSI_r16_enum2value_56,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_maxNumberCLI_RSSI_r16_56 = {
	"maxNumberCLI-RSSI-r16",
	"maxNumberCLI-RSSI-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56,
	sizeof(asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56)
		/sizeof(asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56[0]) - 1, /* 1 */
	asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56,	/* Same as above */
	sizeof(asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56)
		/sizeof(asn_DEF_NR_maxNumberCLI_RSSI_r16_tags_56[0]), /* 2 */
	{ 0, &asn_PER_type_NR_maxNumberCLI_RSSI_r16_constr_56, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_maxNumberCLI_RSSI_r16_specs_56	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_maxNumberCLI_SRS_RSRP_r16_value2enum_61[] = {
	{ 0,	2,	"n4" },
	{ 1,	2,	"n8" },
	{ 2,	3,	"n16" },
	{ 3,	3,	"n32" }
};
static const unsigned int asn_MAP_NR_maxNumberCLI_SRS_RSRP_r16_enum2value_61[] = {
	2,	/* n16(2) */
	3,	/* n32(3) */
	0,	/* n4(0) */
	1	/* n8(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_maxNumberCLI_SRS_RSRP_r16_specs_61 = {
	asn_MAP_NR_maxNumberCLI_SRS_RSRP_r16_value2enum_61,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_maxNumberCLI_SRS_RSRP_r16_enum2value_61,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_61 = {
	"maxNumberCLI-SRS-RSRP-r16",
	"maxNumberCLI-SRS-RSRP-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61,
	sizeof(asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61)
		/sizeof(asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61[0]) - 1, /* 1 */
	asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61,	/* Same as above */
	sizeof(asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61)
		/sizeof(asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_tags_61[0]), /* 2 */
	{ 0, &asn_PER_type_NR_maxNumberCLI_SRS_RSRP_r16_constr_61, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_maxNumberCLI_SRS_RSRP_r16_specs_61	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_value2enum_66[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n4" },
	{ 2,	2,	"n8" }
};
static const unsigned int asn_MAP_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_enum2value_66[] = {
	0,	/* n2(0) */
	1,	/* n4(1) */
	2	/* n8(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_specs_66 = {
	asn_MAP_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_value2enum_66,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_enum2value_66,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_66 = {
	"maxNumberPerSlotCLI-SRS-RSRP-r16",
	"maxNumberPerSlotCLI-SRS-RSRP-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66,
	sizeof(asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66)
		/sizeof(asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66[0]) - 1, /* 1 */
	asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66,	/* Same as above */
	sizeof(asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66)
		/sizeof(asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_tags_66[0]), /* 2 */
	{ 0, &asn_PER_type_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_constr_66, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_specs_66	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_mfbi_IAB_r16_value2enum_70[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_mfbi_IAB_r16_enum2value_70[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_mfbi_IAB_r16_specs_70 = {
	asn_MAP_NR_mfbi_IAB_r16_value2enum_70,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_mfbi_IAB_r16_enum2value_70,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_mfbi_IAB_r16_tags_70[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_mfbi_IAB_r16_70 = {
	"mfbi-IAB-r16",
	"mfbi-IAB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_mfbi_IAB_r16_tags_70,
	sizeof(asn_DEF_NR_mfbi_IAB_r16_tags_70)
		/sizeof(asn_DEF_NR_mfbi_IAB_r16_tags_70[0]) - 1, /* 1 */
	asn_DEF_NR_mfbi_IAB_r16_tags_70,	/* Same as above */
	sizeof(asn_DEF_NR_mfbi_IAB_r16_tags_70)
		/sizeof(asn_DEF_NR_mfbi_IAB_r16_tags_70[0]), /* 2 */
	{ 0, &asn_PER_type_NR_mfbi_IAB_r16_constr_70, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_mfbi_IAB_r16_specs_70	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_multipleNS_And_Pmax_IAB_r16_value2enum_72[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_multipleNS_And_Pmax_IAB_r16_enum2value_72[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_multipleNS_And_Pmax_IAB_r16_specs_72 = {
	asn_MAP_NR_multipleNS_And_Pmax_IAB_r16_value2enum_72,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_multipleNS_And_Pmax_IAB_r16_enum2value_72,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_72 = {
	"multipleNS-And-Pmax-IAB-r16",
	"multipleNS-And-Pmax-IAB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72,
	sizeof(asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72)
		/sizeof(asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72[0]) - 1, /* 1 */
	asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72,	/* Same as above */
	sizeof(asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72)
		/sizeof(asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_tags_72[0]), /* 2 */
	{ 0, &asn_PER_type_NR_multipleNS_And_Pmax_IAB_r16_constr_72, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_multipleNS_And_Pmax_IAB_r16_specs_72	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_nr_CGI_Reporting_NPN_r16_value2enum_74[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_nr_CGI_Reporting_NPN_r16_enum2value_74[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_nr_CGI_Reporting_NPN_r16_specs_74 = {
	asn_MAP_NR_nr_CGI_Reporting_NPN_r16_value2enum_74,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_nr_CGI_Reporting_NPN_r16_enum2value_74,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_nr_CGI_Reporting_NPN_r16_74 = {
	"nr-CGI-Reporting-NPN-r16",
	"nr-CGI-Reporting-NPN-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74,
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74[0]) - 1, /* 1 */
	asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74,	/* Same as above */
	sizeof(asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74)
		/sizeof(asn_DEF_NR_nr_CGI_Reporting_NPN_r16_tags_74[0]), /* 2 */
	{ 0, &asn_PER_type_NR_nr_CGI_Reporting_NPN_r16_constr_74, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_nr_CGI_Reporting_NPN_r16_specs_74	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_idleInactiveEUTRA_MeasReport_r16_value2enum_76[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_idleInactiveEUTRA_MeasReport_r16_enum2value_76[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_idleInactiveEUTRA_MeasReport_r16_specs_76 = {
	asn_MAP_NR_idleInactiveEUTRA_MeasReport_r16_value2enum_76,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_idleInactiveEUTRA_MeasReport_r16_enum2value_76,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_76 = {
	"idleInactiveEUTRA-MeasReport-r16",
	"idleInactiveEUTRA-MeasReport-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76,
	sizeof(asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76)
		/sizeof(asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76[0]) - 1, /* 1 */
	asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76,	/* Same as above */
	sizeof(asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76)
		/sizeof(asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_tags_76[0]), /* 2 */
	{ 0, &asn_PER_type_NR_idleInactiveEUTRA_MeasReport_r16_constr_76, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_idleInactiveEUTRA_MeasReport_r16_specs_76	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_idleInactive_ValidityArea_r16_value2enum_78[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_NR_idleInactive_ValidityArea_r16_enum2value_78[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_idleInactive_ValidityArea_r16_specs_78 = {
	asn_MAP_NR_idleInactive_ValidityArea_r16_value2enum_78,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_idleInactive_ValidityArea_r16_enum2value_78,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_idleInactive_ValidityArea_r16_78 = {
	"idleInactive-ValidityArea-r16",
	"idleInactive-ValidityArea-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78,
	sizeof(asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78)
		/sizeof(asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78[0]) - 1, /* 1 */
	asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78,	/* Same as above */
	sizeof(asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78)
		/sizeof(asn_DEF_NR_idleInactive_ValidityArea_r16_tags_78[0]), /* 2 */
	{ 0, &asn_PER_type_NR_idleInactive_ValidityArea_r16_constr_78, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_idleInactive_ValidityArea_r16_specs_78	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext5_43[] = {
	{ ATF_POINTER, 13, offsetof(struct NR_MeasAndMobParametersCommon__ext5, reportAddNeighMeasForPeriodic_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_reportAddNeighMeasForPeriodic_r16_44,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportAddNeighMeasForPeriodic-r16"
		},
	{ ATF_POINTER, 12, offsetof(struct NR_MeasAndMobParametersCommon__ext5, condHandoverParametersCommon_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_NR_condHandoverParametersCommon_r16_46,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"condHandoverParametersCommon-r16"
		},
	{ ATF_POINTER, 11, offsetof(struct NR_MeasAndMobParametersCommon__ext5, nr_NeedForGap_Reporting_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_NeedForGap_Reporting_r16_51,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-NeedForGap-Reporting-r16"
		},
	{ ATF_POINTER, 10, offsetof(struct NR_MeasAndMobParametersCommon__ext5, supportedGapPattern_NRonly_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_NR_supportedGapPattern_NRonly_r16_constr_53,  memb_NR_supportedGapPattern_NRonly_r16_constraint_43 },
		0, 0, /* No default value */
		"supportedGapPattern-NRonly-r16"
		},
	{ ATF_POINTER, 9, offsetof(struct NR_MeasAndMobParametersCommon__ext5, supportedGapPattern_NRonly_NEDC_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_supportedGapPattern_NRonly_NEDC_r16_54,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedGapPattern-NRonly-NEDC-r16"
		},
	{ ATF_POINTER, 8, offsetof(struct NR_MeasAndMobParametersCommon__ext5, maxNumberCLI_RSSI_r16),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_maxNumberCLI_RSSI_r16_56,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberCLI-RSSI-r16"
		},
	{ ATF_POINTER, 7, offsetof(struct NR_MeasAndMobParametersCommon__ext5, maxNumberCLI_SRS_RSRP_r16),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_maxNumberCLI_SRS_RSRP_r16_61,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberCLI-SRS-RSRP-r16"
		},
	{ ATF_POINTER, 6, offsetof(struct NR_MeasAndMobParametersCommon__ext5, maxNumberPerSlotCLI_SRS_RSRP_r16),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_maxNumberPerSlotCLI_SRS_RSRP_r16_66,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxNumberPerSlotCLI-SRS-RSRP-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct NR_MeasAndMobParametersCommon__ext5, mfbi_IAB_r16),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_mfbi_IAB_r16_70,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mfbi-IAB-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct NR_MeasAndMobParametersCommon__ext5, multipleNS_And_Pmax_IAB_r16),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_multipleNS_And_Pmax_IAB_r16_72,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"multipleNS-And-Pmax-IAB-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_MeasAndMobParametersCommon__ext5, nr_CGI_Reporting_NPN_r16),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_nr_CGI_Reporting_NPN_r16_74,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-CGI-Reporting-NPN-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon__ext5, idleInactiveEUTRA_MeasReport_r16),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_idleInactiveEUTRA_MeasReport_r16_76,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"idleInactiveEUTRA-MeasReport-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon__ext5, idleInactive_ValidityArea_r16),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_idleInactive_ValidityArea_r16_78,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"idleInactive-ValidityArea-r16"
		},
};
static const int asn_MAP_NR_ext5_oms_43[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static const ber_tlv_tag_t asn_DEF_NR_ext5_tags_43[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext5_tag2el_43[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportAddNeighMeasForPeriodic-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* condHandoverParametersCommon-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nr-NeedForGap-Reporting-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* supportedGapPattern-NRonly-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* supportedGapPattern-NRonly-NEDC-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* maxNumberCLI-RSSI-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* maxNumberCLI-SRS-RSRP-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* maxNumberPerSlotCLI-SRS-RSRP-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* mfbi-IAB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* multipleNS-And-Pmax-IAB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* nr-CGI-Reporting-NPN-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* idleInactiveEUTRA-MeasReport-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* idleInactive-ValidityArea-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext5_specs_43 = {
	sizeof(struct NR_MeasAndMobParametersCommon__ext5),
	offsetof(struct NR_MeasAndMobParametersCommon__ext5, _asn_ctx),
	asn_MAP_NR_ext5_tag2el_43,
	13,	/* Count of tags in the map */
	asn_MAP_NR_ext5_oms_43,	/* Optional members */
	13, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext5_43 = {
	"ext5",
	"ext5",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext5_tags_43,
	sizeof(asn_DEF_NR_ext5_tags_43)
		/sizeof(asn_DEF_NR_ext5_tags_43[0]) - 1, /* 1 */
	asn_DEF_NR_ext5_tags_43,	/* Same as above */
	sizeof(asn_DEF_NR_ext5_tags_43)
		/sizeof(asn_DEF_NR_ext5_tags_43[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext5_43,
	13,	/* Elements count */
	&asn_SPC_NR_ext5_specs_43	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NR_MeasAndMobParametersCommon_1[] = {
	{ ATF_POINTER, 8, offsetof(struct NR_MeasAndMobParametersCommon, supportedGapPattern),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_NR_supportedGapPattern_constr_2,  memb_NR_supportedGapPattern_constraint_1 },
		0, 0, /* No default value */
		"supportedGapPattern"
		},
	{ ATF_POINTER, 7, offsetof(struct NR_MeasAndMobParametersCommon, ssb_RLM),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_ssb_RLM_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-RLM"
		},
	{ ATF_POINTER, 6, offsetof(struct NR_MeasAndMobParametersCommon, ssb_AndCSI_RS_RLM),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_ssb_AndCSI_RS_RLM_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssb-AndCSI-RS-RLM"
		},
	{ ATF_POINTER, 5, offsetof(struct NR_MeasAndMobParametersCommon, ext1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_NR_ext1_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_POINTER, 4, offsetof(struct NR_MeasAndMobParametersCommon, ext2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_NR_ext2_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext2"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_MeasAndMobParametersCommon, ext3),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_NR_ext3_31,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext3"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_MeasAndMobParametersCommon, ext4),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_NR_ext4_34,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext4"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_MeasAndMobParametersCommon, ext5),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_NR_ext5_43,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext5"
		},
};
static const int asn_MAP_NR_MeasAndMobParametersCommon_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_NR_MeasAndMobParametersCommon_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_MeasAndMobParametersCommon_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedGapPattern */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssb-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ssb-AndCSI-RS-RLM */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ext2 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ext3 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ext4 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* ext5 */
};
asn_SEQUENCE_specifics_t asn_SPC_NR_MeasAndMobParametersCommon_specs_1 = {
	sizeof(struct NR_MeasAndMobParametersCommon),
	offsetof(struct NR_MeasAndMobParametersCommon, _asn_ctx),
	asn_MAP_NR_MeasAndMobParametersCommon_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_NR_MeasAndMobParametersCommon_oms_1,	/* Optional members */
	3, 5,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NR_MeasAndMobParametersCommon = {
	"MeasAndMobParametersCommon",
	"MeasAndMobParametersCommon",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_MeasAndMobParametersCommon_tags_1,
	sizeof(asn_DEF_NR_MeasAndMobParametersCommon_tags_1)
		/sizeof(asn_DEF_NR_MeasAndMobParametersCommon_tags_1[0]), /* 1 */
	asn_DEF_NR_MeasAndMobParametersCommon_tags_1,	/* Same as above */
	sizeof(asn_DEF_NR_MeasAndMobParametersCommon_tags_1)
		/sizeof(asn_DEF_NR_MeasAndMobParametersCommon_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_MeasAndMobParametersCommon_1,
	8,	/* Elements count */
	&asn_SPC_NR_MeasAndMobParametersCommon_specs_1	/* Additional specs */
};

