/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-InterNodeDefinitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_MeasurementTimingConfiguration_v1610_IEs_H_
#define	_NR_MeasurementTimingConfiguration_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR_SubcarrierSpacing.h"
#include "NR_CSI-RS-CellMobility.h"
#include "NR_ARFCN-ValueNR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NR_MeasurementTimingConfiguration-v1610-IEs */
typedef struct NR_MeasurementTimingConfiguration_v1610_IEs {
	struct NR_MeasurementTimingConfiguration_v1610_IEs__csi_RS_Config_r16 {
		NR_SubcarrierSpacing_t	 csi_RS_SubcarrierSpacing_r16;
		NR_CSI_RS_CellMobility_t	 csi_RS_CellMobility_r16;
		NR_ARFCN_ValueNR_t	 refSSBFreq_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} csi_RS_Config_r16;
	struct NR_MeasurementTimingConfiguration_v1610_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_MeasurementTimingConfiguration_v1610_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_MeasurementTimingConfiguration_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_MeasurementTimingConfiguration_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_MeasurementTimingConfiguration_v1610_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_MeasurementTimingConfiguration_v1610_IEs_H_ */
#include <asn_internal.h>
