/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_OverheatingAssistance_H_
#define	_NR_OverheatingAssistance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR_MIMO-LayersDL.h"
#include "NR_MIMO-LayersUL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NR_ReducedMaxCCs_r16;
struct NR_ReducedMaxBW_FRx_r16;

/* NR_OverheatingAssistance */
typedef struct NR_OverheatingAssistance {
	struct NR_ReducedMaxCCs_r16	*reducedMaxCCs;	/* OPTIONAL */
	struct NR_ReducedMaxBW_FRx_r16	*reducedMaxBW_FR1;	/* OPTIONAL */
	struct NR_ReducedMaxBW_FRx_r16	*reducedMaxBW_FR2;	/* OPTIONAL */
	struct NR_OverheatingAssistance__reducedMaxMIMO_LayersFR1 {
		NR_MIMO_LayersDL_t	 reducedMIMO_LayersFR1_DL;
		NR_MIMO_LayersUL_t	 reducedMIMO_LayersFR1_UL;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reducedMaxMIMO_LayersFR1;
	struct NR_OverheatingAssistance__reducedMaxMIMO_LayersFR2 {
		NR_MIMO_LayersDL_t	 reducedMIMO_LayersFR2_DL;
		NR_MIMO_LayersUL_t	 reducedMIMO_LayersFR2_UL;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reducedMaxMIMO_LayersFR2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_OverheatingAssistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_OverheatingAssistance;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_OverheatingAssistance_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_OverheatingAssistance_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NR_ReducedMaxCCs-r16.h"
#include "NR_ReducedMaxBW-FRx-r16.h"

#endif	/* _NR_OverheatingAssistance_H_ */
#include <asn_internal.h>
