/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#include "NR_PDCCH-ServingCellConfig.h"

static int
memb_NR_searchSpaceSwitchingTimer_r16_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 80)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_NR_searchSpaceSwitchingTimer_r16_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  1,  80 }	/* (1..80) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_NR_ext1_4[] = {
	{ ATF_POINTER, 2, offsetof(struct NR_PDCCH_ServingCellConfig__ext1, availabilityIndicator_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NR_SetupRelease_AvailabilityIndicator_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"availabilityIndicator-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_PDCCH_ServingCellConfig__ext1, searchSpaceSwitchingTimer_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_searchSpaceSwitchingTimer_r16_constr_6,  memb_NR_searchSpaceSwitchingTimer_r16_constraint_4 },
		0, 0, /* No default value */
		"searchSpaceSwitchingTimer-r16"
		},
};
static const int asn_MAP_NR_ext1_oms_4[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NR_ext1_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext1_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* availabilityIndicator-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* searchSpaceSwitchingTimer-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext1_specs_4 = {
	sizeof(struct NR_PDCCH_ServingCellConfig__ext1),
	offsetof(struct NR_PDCCH_ServingCellConfig__ext1, _asn_ctx),
	asn_MAP_NR_ext1_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_NR_ext1_oms_4,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext1_4 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext1_tags_4,
	sizeof(asn_DEF_NR_ext1_tags_4)
		/sizeof(asn_DEF_NR_ext1_tags_4[0]) - 1, /* 1 */
	asn_DEF_NR_ext1_tags_4,	/* Same as above */
	sizeof(asn_DEF_NR_ext1_tags_4)
		/sizeof(asn_DEF_NR_ext1_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext1_4,
	2,	/* Elements count */
	&asn_SPC_NR_ext1_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NR_PDCCH_ServingCellConfig_1[] = {
	{ ATF_POINTER, 2, offsetof(struct NR_PDCCH_ServingCellConfig, slotFormatIndicator),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NR_SetupRelease_SlotFormatIndicator,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"slotFormatIndicator"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_PDCCH_ServingCellConfig, ext1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_NR_ext1_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
};
static const int asn_MAP_NR_PDCCH_ServingCellConfig_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NR_PDCCH_ServingCellConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_PDCCH_ServingCellConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* slotFormatIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ext1 */
};
asn_SEQUENCE_specifics_t asn_SPC_NR_PDCCH_ServingCellConfig_specs_1 = {
	sizeof(struct NR_PDCCH_ServingCellConfig),
	offsetof(struct NR_PDCCH_ServingCellConfig, _asn_ctx),
	asn_MAP_NR_PDCCH_ServingCellConfig_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NR_PDCCH_ServingCellConfig_oms_1,	/* Optional members */
	1, 1,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NR_PDCCH_ServingCellConfig = {
	"PDCCH-ServingCellConfig",
	"PDCCH-ServingCellConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_PDCCH_ServingCellConfig_tags_1,
	sizeof(asn_DEF_NR_PDCCH_ServingCellConfig_tags_1)
		/sizeof(asn_DEF_NR_PDCCH_ServingCellConfig_tags_1[0]), /* 1 */
	asn_DEF_NR_PDCCH_ServingCellConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_NR_PDCCH_ServingCellConfig_tags_1)
		/sizeof(asn_DEF_NR_PDCCH_ServingCellConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_PDCCH_ServingCellConfig_1,
	2,	/* Elements count */
	&asn_SPC_NR_PDCCH_ServingCellConfig_specs_1	/* Additional specs */
};

