/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_RRCSystemInfoRequest_H_
#define	_NR_RRCSystemInfoRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_RRCSystemInfoRequest__criticalExtensions_PR {
	NR_RRCSystemInfoRequest__criticalExtensions_PR_NOTHING,	/* No components present */
	NR_RRCSystemInfoRequest__criticalExtensions_PR_rrcSystemInfoRequest,
	NR_RRCSystemInfoRequest__criticalExtensions_PR_criticalExtensionsFuture_r16
} NR_RRCSystemInfoRequest__criticalExtensions_PR;
typedef enum NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR {
	NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR_NOTHING,	/* No components present */
	NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR_rrcPosSystemInfoRequest_r16,
	NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR_criticalExtensionsFuture
} NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR;

/* Forward declarations */
struct NR_RRCSystemInfoRequest_IEs;
struct NR_RRC_PosSystemInfoRequest_r16_IEs;

/* NR_RRCSystemInfoRequest */
typedef struct NR_RRCSystemInfoRequest {
	struct NR_RRCSystemInfoRequest__criticalExtensions {
		NR_RRCSystemInfoRequest__criticalExtensions_PR present;
		union NR_RRCSystemInfoRequest__NR_criticalExtensions_u {
			struct NR_RRCSystemInfoRequest_IEs	*rrcSystemInfoRequest;
			struct NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16 {
				NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16_PR present;
				union NR_RRCSystemInfoRequest__NR_criticalExtensions__NR_criticalExtensionsFuture_r16_u {
					struct NR_RRC_PosSystemInfoRequest_r16_IEs	*rrcPosSystemInfoRequest_r16;
					struct NR_RRCSystemInfoRequest__criticalExtensions__criticalExtensionsFuture_r16__criticalExtensionsFuture {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *criticalExtensionsFuture;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture_r16;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_RRCSystemInfoRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_RRCSystemInfoRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_RRCSystemInfoRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_RRCSystemInfoRequest_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NR_RRCSystemInfoRequest-IEs.h"
#include "NR_RRC-PosSystemInfoRequest-r16-IEs.h"

#endif	/* _NR_RRCSystemInfoRequest_H_ */
#include <asn_internal.h>
