/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#include "NR_SL-ConfiguredGrantConfig-r16.h"

static int
memb_NR_sl_TimeResourceCG_Type1_r16_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 496)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_StartSubchannelCG_Type1_r16_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 26)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_FreqResourceCG_Type1_r16_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 6929)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_TimeOffsetCG_Type1_r16_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7999)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_PSFCH_ToPUCCH_CG_Type1_r16_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_NrOfHARQ_Processes_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NR_sl_HARQ_ProcID_offset_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_NR_sl_TimeResourceCG_Type1_r16_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  496 }	/* (0..496) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_StartSubchannelCG_Type1_r16_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  26 }	/* (0..26) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_FreqResourceCG_Type1_r16_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 13,  13,  0,  6929 }	/* (0..6929) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_TimeOffsetCG_Type1_r16_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 13,  13,  0,  7999 }	/* (0..7999) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_PSFCH_ToPUCCH_CG_Type1_r16_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_NrOfHARQ_Processes_r16_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_NR_sl_HARQ_ProcID_offset_r16_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_NR_rrc_ConfiguredSidelinkGrant_7[] = {
	{ ATF_POINTER, 6, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_TimeResourceCG_Type1_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_TimeResourceCG_Type1_r16_constr_8,  memb_NR_sl_TimeResourceCG_Type1_r16_constraint_7 },
		0, 0, /* No default value */
		"sl-TimeResourceCG-Type1-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_StartSubchannelCG_Type1_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_StartSubchannelCG_Type1_r16_constr_9,  memb_NR_sl_StartSubchannelCG_Type1_r16_constraint_7 },
		0, 0, /* No default value */
		"sl-StartSubchannelCG-Type1-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_FreqResourceCG_Type1_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_FreqResourceCG_Type1_r16_constr_10,  memb_NR_sl_FreqResourceCG_Type1_r16_constraint_7 },
		0, 0, /* No default value */
		"sl-FreqResourceCG-Type1-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_TimeOffsetCG_Type1_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_TimeOffsetCG_Type1_r16_constr_11,  memb_NR_sl_TimeOffsetCG_Type1_r16_constraint_7 },
		0, 0, /* No default value */
		"sl-TimeOffsetCG-Type1-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_N1PUCCH_AN_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_PUCCH_ResourceId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-N1PUCCH-AN-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, sl_PSFCH_ToPUCCH_CG_Type1_r16),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_PSFCH_ToPUCCH_CG_Type1_r16_constr_13,  memb_NR_sl_PSFCH_ToPUCCH_CG_Type1_r16_constraint_7 },
		0, 0, /* No default value */
		"sl-PSFCH-ToPUCCH-CG-Type1-r16"
		},
};
static const int asn_MAP_NR_rrc_ConfiguredSidelinkGrant_oms_7[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_rrc_ConfiguredSidelinkGrant_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-TimeResourceCG-Type1-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl-StartSubchannelCG-Type1-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sl-FreqResourceCG-Type1-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sl-TimeOffsetCG-Type1-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sl-N1PUCCH-AN-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* sl-PSFCH-ToPUCCH-CG-Type1-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_rrc_ConfiguredSidelinkGrant_specs_7 = {
	sizeof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant),
	offsetof(struct NR_SL_ConfiguredGrantConfig_r16__rrc_ConfiguredSidelinkGrant, _asn_ctx),
	asn_MAP_NR_rrc_ConfiguredSidelinkGrant_tag2el_7,
	6,	/* Count of tags in the map */
	asn_MAP_NR_rrc_ConfiguredSidelinkGrant_oms_7,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_rrc_ConfiguredSidelinkGrant_7 = {
	"rrc-ConfiguredSidelinkGrant",
	"rrc-ConfiguredSidelinkGrant",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7,
	sizeof(asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7)
		/sizeof(asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7[0]) - 1, /* 1 */
	asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7,	/* Same as above */
	sizeof(asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7)
		/sizeof(asn_DEF_NR_rrc_ConfiguredSidelinkGrant_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_rrc_ConfiguredSidelinkGrant_7,
	6,	/* Elements count */
	&asn_SPC_NR_rrc_ConfiguredSidelinkGrant_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NR_SL_ConfiguredGrantConfig_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, sl_ConfigIndexCG_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_SL_ConfigIndexCG_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-ConfigIndexCG-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, sl_PeriodCG_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NR_SL_PeriodCG_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-PeriodCG-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, sl_NrOfHARQ_Processes_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_NrOfHARQ_Processes_r16_constr_4,  memb_NR_sl_NrOfHARQ_Processes_r16_constraint_1 },
		0, 0, /* No default value */
		"sl-NrOfHARQ-Processes-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, sl_HARQ_ProcID_offset_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_NR_sl_HARQ_ProcID_offset_r16_constr_5,  memb_NR_sl_HARQ_ProcID_offset_r16_constraint_1 },
		0, 0, /* No default value */
		"sl-HARQ-ProcID-offset-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, sl_CG_MaxTransNumList_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_SL_CG_MaxTransNumList_r16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-CG-MaxTransNumList-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_SL_ConfiguredGrantConfig_r16, rrc_ConfiguredSidelinkGrant),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_NR_rrc_ConfiguredSidelinkGrant_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rrc-ConfiguredSidelinkGrant"
		},
};
static const int asn_MAP_NR_SL_ConfiguredGrantConfig_r16_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_SL_ConfiguredGrantConfig_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-ConfigIndexCG-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl-PeriodCG-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sl-NrOfHARQ-Processes-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sl-HARQ-ProcID-offset-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sl-CG-MaxTransNumList-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* rrc-ConfiguredSidelinkGrant */
};
asn_SEQUENCE_specifics_t asn_SPC_NR_SL_ConfiguredGrantConfig_r16_specs_1 = {
	sizeof(struct NR_SL_ConfiguredGrantConfig_r16),
	offsetof(struct NR_SL_ConfiguredGrantConfig_r16, _asn_ctx),
	asn_MAP_NR_SL_ConfiguredGrantConfig_r16_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_NR_SL_ConfiguredGrantConfig_r16_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NR_SL_ConfiguredGrantConfig_r16 = {
	"SL-ConfiguredGrantConfig-r16",
	"SL-ConfiguredGrantConfig-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1,
	sizeof(asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1)
		/sizeof(asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1[0]), /* 1 */
	asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1)
		/sizeof(asn_DEF_NR_SL_ConfiguredGrantConfig_r16_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_SL_ConfiguredGrantConfig_r16_1,
	6,	/* Elements count */
	&asn_SPC_NR_SL_ConfiguredGrantConfig_r16_specs_1	/* Additional specs */
};

