/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#include "NR_SCellConfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_NR_sCellState_r16_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_NR_secondaryDRX_GroupConfig_r16_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_NR_ext1_6[] = {
	{ ATF_POINTER, 1, offsetof(struct NR_SCellConfig__ext1, smtc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_SSB_MTC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smtc"
		},
};
static const int asn_MAP_NR_ext1_oms_6[] = { 0 };
static const ber_tlv_tag_t asn_DEF_NR_ext1_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext1_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* smtc */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext1_specs_6 = {
	sizeof(struct NR_SCellConfig__ext1),
	offsetof(struct NR_SCellConfig__ext1, _asn_ctx),
	asn_MAP_NR_ext1_tag2el_6,
	1,	/* Count of tags in the map */
	asn_MAP_NR_ext1_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext1_6 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext1_tags_6,
	sizeof(asn_DEF_NR_ext1_tags_6)
		/sizeof(asn_DEF_NR_ext1_tags_6[0]) - 1, /* 1 */
	asn_DEF_NR_ext1_tags_6,	/* Same as above */
	sizeof(asn_DEF_NR_ext1_tags_6)
		/sizeof(asn_DEF_NR_ext1_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext1_6,
	1,	/* Elements count */
	&asn_SPC_NR_ext1_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_sCellState_r16_value2enum_9[] = {
	{ 0,	9,	"activated" }
};
static const unsigned int asn_MAP_NR_sCellState_r16_enum2value_9[] = {
	0	/* activated(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_sCellState_r16_specs_9 = {
	asn_MAP_NR_sCellState_r16_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_sCellState_r16_enum2value_9,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_sCellState_r16_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_sCellState_r16_9 = {
	"sCellState-r16",
	"sCellState-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_sCellState_r16_tags_9,
	sizeof(asn_DEF_NR_sCellState_r16_tags_9)
		/sizeof(asn_DEF_NR_sCellState_r16_tags_9[0]) - 1, /* 1 */
	asn_DEF_NR_sCellState_r16_tags_9,	/* Same as above */
	sizeof(asn_DEF_NR_sCellState_r16_tags_9)
		/sizeof(asn_DEF_NR_sCellState_r16_tags_9[0]), /* 2 */
	{ 0, &asn_PER_type_NR_sCellState_r16_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_sCellState_r16_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_NR_secondaryDRX_GroupConfig_r16_value2enum_11[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_NR_secondaryDRX_GroupConfig_r16_enum2value_11[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_NR_secondaryDRX_GroupConfig_r16_specs_11 = {
	asn_MAP_NR_secondaryDRX_GroupConfig_r16_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_NR_secondaryDRX_GroupConfig_r16_enum2value_11,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_secondaryDRX_GroupConfig_r16_11 = {
	"secondaryDRX-GroupConfig-r16",
	"secondaryDRX-GroupConfig-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11,
	sizeof(asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11)
		/sizeof(asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11[0]) - 1, /* 1 */
	asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11,	/* Same as above */
	sizeof(asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11)
		/sizeof(asn_DEF_NR_secondaryDRX_GroupConfig_r16_tags_11[0]), /* 2 */
	{ 0, &asn_PER_type_NR_secondaryDRX_GroupConfig_r16_constr_11, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NR_secondaryDRX_GroupConfig_r16_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_NR_ext2_8[] = {
	{ ATF_POINTER, 2, offsetof(struct NR_SCellConfig__ext2, sCellState_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_sCellState_r16_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellState-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_SCellConfig__ext2, secondaryDRX_GroupConfig_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_secondaryDRX_GroupConfig_r16_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"secondaryDRX-GroupConfig-r16"
		},
};
static const int asn_MAP_NR_ext2_oms_8[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NR_ext2_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_ext2_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sCellState-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* secondaryDRX-GroupConfig-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NR_ext2_specs_8 = {
	sizeof(struct NR_SCellConfig__ext2),
	offsetof(struct NR_SCellConfig__ext2, _asn_ctx),
	asn_MAP_NR_ext2_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_NR_ext2_oms_8,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NR_ext2_8 = {
	"ext2",
	"ext2",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_ext2_tags_8,
	sizeof(asn_DEF_NR_ext2_tags_8)
		/sizeof(asn_DEF_NR_ext2_tags_8[0]) - 1, /* 1 */
	asn_DEF_NR_ext2_tags_8,	/* Same as above */
	sizeof(asn_DEF_NR_ext2_tags_8)
		/sizeof(asn_DEF_NR_ext2_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_ext2_8,
	2,	/* Elements count */
	&asn_SPC_NR_ext2_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NR_SCellConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NR_SCellConfig, sCellIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_SCellIndex,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellIndex"
		},
	{ ATF_POINTER, 4, offsetof(struct NR_SCellConfig, sCellConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_ServingCellConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellConfigCommon"
		},
	{ ATF_POINTER, 3, offsetof(struct NR_SCellConfig, sCellConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_ServingCellConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellConfigDedicated"
		},
	{ ATF_POINTER, 2, offsetof(struct NR_SCellConfig, ext1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_NR_ext1_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_POINTER, 1, offsetof(struct NR_SCellConfig, ext2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_NR_ext2_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext2"
		},
};
static const int asn_MAP_NR_SCellConfig_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_NR_SCellConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NR_SCellConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sCellIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sCellConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sCellConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ext2 */
};
asn_SEQUENCE_specifics_t asn_SPC_NR_SCellConfig_specs_1 = {
	sizeof(struct NR_SCellConfig),
	offsetof(struct NR_SCellConfig, _asn_ctx),
	asn_MAP_NR_SCellConfig_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_NR_SCellConfig_oms_1,	/* Optional members */
	2, 2,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NR_SCellConfig = {
	"SCellConfig",
	"SCellConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_NR_SCellConfig_tags_1,
	sizeof(asn_DEF_NR_SCellConfig_tags_1)
		/sizeof(asn_DEF_NR_SCellConfig_tags_1[0]), /* 1 */
	asn_DEF_NR_SCellConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_NR_SCellConfig_tags_1)
		/sizeof(asn_DEF_NR_SCellConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NR_SCellConfig_1,
	5,	/* Elements count */
	&asn_SPC_NR_SCellConfig_specs_1	/* Additional specs */
};

