/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_SL_UE_SelectedConfigRP_r16_H_
#define	_NR_SL_UE_SelectedConfigRP_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_SL_UE_SelectedConfigRP_r16__sl_MultiReserveResource_r16 {
	NR_SL_UE_SelectedConfigRP_r16__sl_MultiReserveResource_r16_enabled	= 0
} e_NR_SL_UE_SelectedConfigRP_r16__sl_MultiReserveResource_r16;
typedef enum NR_SL_UE_SelectedConfigRP_r16__sl_MaxNumPerReserve_r16 {
	NR_SL_UE_SelectedConfigRP_r16__sl_MaxNumPerReserve_r16_n2	= 0,
	NR_SL_UE_SelectedConfigRP_r16__sl_MaxNumPerReserve_r16_n3	= 1
} e_NR_SL_UE_SelectedConfigRP_r16__sl_MaxNumPerReserve_r16;
typedef enum NR_SL_UE_SelectedConfigRP_r16__sl_SensingWindow_r16 {
	NR_SL_UE_SelectedConfigRP_r16__sl_SensingWindow_r16_ms100	= 0,
	NR_SL_UE_SelectedConfigRP_r16__sl_SensingWindow_r16_ms1100	= 1
} e_NR_SL_UE_SelectedConfigRP_r16__sl_SensingWindow_r16;
typedef enum NR_SL_UE_SelectedConfigRP_r16__sl_RS_ForSensing_r16 {
	NR_SL_UE_SelectedConfigRP_r16__sl_RS_ForSensing_r16_pscch	= 0,
	NR_SL_UE_SelectedConfigRP_r16__sl_RS_ForSensing_r16_pssch	= 1
} e_NR_SL_UE_SelectedConfigRP_r16__sl_RS_ForSensing_r16;

/* Forward declarations */
struct NR_SL_CBR_PriorityTxConfigList_r16;
struct NR_SL_ThresPSSCH_RSRP_List_r16;
struct NR_SL_SelectionWindowList_r16;
struct NR_SL_ResourceReservePeriod_r16;

/* NR_SL-UE-SelectedConfigRP-r16 */
typedef struct NR_SL_UE_SelectedConfigRP_r16 {
	struct NR_SL_CBR_PriorityTxConfigList_r16	*sl_CBR_PriorityTxConfigList_r16;	/* OPTIONAL */
	struct NR_SL_ThresPSSCH_RSRP_List_r16	*sl_ThresPSSCH_RSRP_List_r16;	/* OPTIONAL */
	long	*sl_MultiReserveResource_r16;	/* OPTIONAL */
	long	*sl_MaxNumPerReserve_r16;	/* OPTIONAL */
	long	*sl_SensingWindow_r16;	/* OPTIONAL */
	struct NR_SL_SelectionWindowList_r16	*sl_SelectionWindowList_r16;	/* OPTIONAL */
	struct NR_SL_UE_SelectedConfigRP_r16__sl_ResourceReservePeriodList_r16 {
		A_SEQUENCE_OF(struct NR_SL_ResourceReservePeriod_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_ResourceReservePeriodList_r16;
	long	 sl_RS_ForSensing_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_SL_UE_SelectedConfigRP_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_sl_MultiReserveResource_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_sl_MaxNumPerReserve_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_sl_SensingWindow_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_sl_RS_ForSensing_r16_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NR_SL_UE_SelectedConfigRP_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_SL_UE_SelectedConfigRP_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_SL_UE_SelectedConfigRP_r16_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NR_SL-CBR-PriorityTxConfigList-r16.h"
#include "NR_SL-ThresPSSCH-RSRP-List-r16.h"
#include "NR_SL-SelectionWindowList-r16.h"
#include "NR_SL-ResourceReservePeriod-r16.h"

#endif	/* _NR_SL_UE_SelectedConfigRP_r16_H_ */
#include <asn_internal.h>
