/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_SemiStaticChannelAccessConfig_H_
#define	_NR_SemiStaticChannelAccessConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_SemiStaticChannelAccessConfig__period {
	NR_SemiStaticChannelAccessConfig__period_ms1	= 0,
	NR_SemiStaticChannelAccessConfig__period_ms2	= 1,
	NR_SemiStaticChannelAccessConfig__period_ms2dot5	= 2,
	NR_SemiStaticChannelAccessConfig__period_ms4	= 3,
	NR_SemiStaticChannelAccessConfig__period_ms5	= 4,
	NR_SemiStaticChannelAccessConfig__period_ms10	= 5
} e_NR_SemiStaticChannelAccessConfig__period;

/* NR_SemiStaticChannelAccessConfig */
typedef struct NR_SemiStaticChannelAccessConfig {
	long	 period;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_SemiStaticChannelAccessConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_period_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NR_SemiStaticChannelAccessConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_SemiStaticChannelAccessConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_SemiStaticChannelAccessConfig_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_SemiStaticChannelAccessConfig_H_ */
#include <asn_internal.h>
