/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_SSB_MTC_H_
#define	_NR_SSB_MTC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_SSB_MTC__periodicityAndOffset_PR {
	NR_SSB_MTC__periodicityAndOffset_PR_NOTHING,	/* No components present */
	NR_SSB_MTC__periodicityAndOffset_PR_sf5,
	NR_SSB_MTC__periodicityAndOffset_PR_sf10,
	NR_SSB_MTC__periodicityAndOffset_PR_sf20,
	NR_SSB_MTC__periodicityAndOffset_PR_sf40,
	NR_SSB_MTC__periodicityAndOffset_PR_sf80,
	NR_SSB_MTC__periodicityAndOffset_PR_sf160
} NR_SSB_MTC__periodicityAndOffset_PR;
typedef enum NR_SSB_MTC__duration {
	NR_SSB_MTC__duration_sf1	= 0,
	NR_SSB_MTC__duration_sf2	= 1,
	NR_SSB_MTC__duration_sf3	= 2,
	NR_SSB_MTC__duration_sf4	= 3,
	NR_SSB_MTC__duration_sf5	= 4
} e_NR_SSB_MTC__duration;

/* NR_SSB-MTC */
typedef struct NR_SSB_MTC {
	struct NR_SSB_MTC__periodicityAndOffset {
		NR_SSB_MTC__periodicityAndOffset_PR present;
		union NR_SSB_MTC__NR_periodicityAndOffset_u {
			long	 sf5;
			long	 sf10;
			long	 sf20;
			long	 sf40;
			long	 sf80;
			long	 sf160;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} periodicityAndOffset;
	long	 duration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_SSB_MTC_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NR_duration_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NR_SSB_MTC;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_SSB_MTC_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_SSB_MTC_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_SSB_MTC_H_ */
#include <asn_internal.h>
