/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "nr-rrc-16.1.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -findirect-choice -D nr-rrc-16.1.0.gen`
 */

#ifndef	_NR_UplinkConfigCommonSIB_H_
#define	_NR_UplinkConfigCommonSIB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR_FrequencyInfoUL-SIB.h"
#include "NR_BWP-UplinkCommon.h"
#include "NR_TimeAlignmentTimer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NR_UplinkConfigCommonSIB */
typedef struct NR_UplinkConfigCommonSIB {
	NR_FrequencyInfoUL_SIB_t	 frequencyInfoUL;
	NR_BWP_UplinkCommon_t	 initialUplinkBWP;
	NR_TimeAlignmentTimer_t	 timeAlignmentTimerCommon;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_UplinkConfigCommonSIB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_UplinkConfigCommonSIB;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_UplinkConfigCommonSIB_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_UplinkConfigCommonSIB_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_UplinkConfigCommonSIB_H_ */
#include <asn_internal.h>
